In [1]:
import os
import pandas as pd
from transformers import pipeline
import numpy as np

In [2]:
df = pd.read_csv('../data/sentiment_analysis_data.csv', encoding='utf-8')
print("Length of df with NaN texts:", len(df))
df = df.drop(columns=['sentiment'])
df = df.loc[~df['text'].isnull()]
print("Updated length of df without NaN texts:", len(df))
df.head()

Length of df with NaN texts: 1747383
Updated length of df without NaN texts: 1505998

,text,comments,echoes,upvotes,impressions,file
0,Scum of the earth.,532,2933,3562,114,00000fc2fb034a6f8e2d2d7f947201f5
1,WOW. My @Name Hidden car parade must have 10...,90,467,1205,45872,00002078c92a405992fb07e77f3dbdc4
2,White House: Trump Signs Memo to Block Antifa ...,3,71,236,16636,0000210744224756a61de96f7dc440a4
3,Can't you just feel the sheer panic from Democ...,2992,8353,23994,1409093,0000227d9f1e42769a971f2c45260323
4,Looking at all the pictures from the people wh...,19,53,126,5118,0000276e197948d8a6a043236dfc5a68

In [3]:
df['subjectivity'] = [np.nan]*len(df)
df['polarity'] = [np.nan]*len(df)
df['emotion'] = [np.nan]*len(df)
df.head()

,text,comments,echoes,upvotes,impressions,file,subjectivity,polarity,emotion
0,Scum of the earth.,532,2933,3562,114,00000fc2fb034a6f8e2d2d7f947201f5,NaN,NaN,NaN
1,WOW. My @Name Hidden car parade must have 10...,90,467,1205,45872,00002078c92a405992fb07e77f3dbdc4,NaN,NaN,NaN
2,White House: Trump Signs Memo to Block Antifa ...,3,71,236,16636,0000210744224756a61de96f7dc440a4,NaN,NaN,NaN
3,Can't you just feel the sheer panic from Democ...,2992,8353,23994,1409093,0000227d9f1e42769a971f2c45260323,NaN,NaN,NaN
4,Looking at all the pictures from the people wh...,19,53,126,5118,0000276e197948d8a6a043236dfc5a68,NaN,NaN,NaN

In [4]:
df.to_csv('../data/step1.csv', index=False)